#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Float_Menu.Resource", IsApplication=true)]

namespace Float_Menu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int action_button_content_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int action_button_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int action_button_size = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int action_menu_radius = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int sub_action_button_content_margin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int sub_action_button_size = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_note_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_action = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_action_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_action_dark_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_action_dark_touch = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_action_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_action_touch = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_sub_action = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_sub_action_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_sub_action_dark_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_sub_action_dark_touch = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int button_sub_action_selector = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_sub_action_touch = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int delete_red = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
